name: pw_loc
channels:
  - pyg
  - pytorch
  - conda-forge
dependencies:
  - ax-platform=0.2  
  - networkx=2.8
  - numpy=1.23
  - pandas=1.5
  - pip=22.3
  - pyg=2.2
  - python=3.10
  - pytorch=1.13
  - scikit-learn=1.1
  - scikit-optimize=0.9
  - seaborn=0.12
  - bioconda::snakemake-minimal=7.18
