name: pw_loc
channels:
  - pyg
  - pytorch
  - conda-forge
dependencies:
  - networkx
  - numpy
  - pandas
  - pip
  - pyg
  - python
  - pytorch
  - scikit-learn
  - scikit-optimize
  - seaborn
  - bioconda::snakemake-minimal
